name: Publish package to npm
on:
  workflow_dispatch: # trigger manually
    inputs:
      dry_run:
        description: "NPM release dry-run"
        required: true
        default: "true"

jobs:
  build:
    runs-on: [self-hosted, ubuntu-22-04, regular]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Dry Run Status
        id: dry_run
        run: |
          if [[ ${{ inputs.dry_run }} == true ]]; then
            echo "Running NPM release in dry-run mode"
            echo "dry_run=--dry-run" >> $GITHUB_OUTPUT
          else
            echo "Running NPM release in production mode"
            echo "dry_run=" >> $GITHUB_OUTPUT
          fi

      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        id: secrets
        with:
          url: https://puppet-vault.gc.onl
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/project_fastedge/npmjs token | NPM_TOKEN

      - name: Publish to NPM
        run: npm publish ${{ steps.dry_run.outputs.dry_run }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ steps.secrets.outputs.NPM_TOKEN }}
