name: Pull Request Requirements

on:
  pull_request:
    branches: ["*.*.x", "*.x", "master", "next", "next-major", "beta", "alpha"]

jobs:
  unit_tests:
    runs-on: [self-hosted, ubuntu-22-04, regular]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: npm run asbuild

      - name: Build and run Auth example
        run: cd examples/auth && npm install && npm run asbuild

      - name: Build and run Add Header example
        run: cd examples/addheader && npm install && npm run asbuild
